couchbaselabs/observability

- README.md
- microlith/Dockerfile
The path reorganisation in the cbmultimanager repo broke the microlith build. This PR fixes it. It also wraps creation of cmos-release.txt in a proprietary block, because that currently doesn't work in OSS.
Test Plan:
* Build the proprietary container (`docker build -t couchbase/cmos microlith`), verify it doesn't fail, verify running it (`docker run --rm -it couchbase/cmos:v1`) doesn't error
* Build the OSS container (`tools/build-oss-container.sh)`, verify it doesn't fail, verify running itverify running it (`docker run --rm -it couchbase/oss-cmos:v1`) doesn't error
> CMOS-26: Fix microlith build

- microlith/Dockerfile
- microlith/html/index.html
As part of CMOS-16 we reorganised the build paths for the UI, which broke it in a reverse proxy context. This patch fixes those by building the UI to account for its `/couchbase/` prefix.
Test Plan:
* Build the CMOS image, run it with `-p 8080:8080`, verify you can access the static HTML page, click on the "Couchbase Cluster Monitor Link", and get the UI
* Build the OSS image as a sanity check (this only affects non-OSS parts)
> CMOS-28: fix UI paths

- microlith/README.md
- microlith/entrypoints/prometheus.sh
- microlith/prometheus/prometheus-template.yml
Currently there's no way to provide authentication credentials for the Couchbase Server /metrics endpoint, short of building your own microlith image with them hardcoded.
This commit adds two environment variables, CB_SERVER_AUTH_USER and CB_SERVER_AUTH_PASSWORD, that get substituted as part of the Prometheus startup process.
> CMOS-60 Add env vars for Couchbase Server basic auth

- microlith/Dockerfile
- microlith/run.sh
- microlith/scripts/install-grafana-plugins.sh
- testing/bats/smoke/grafana-plugins.bats
Ensure we install the Grafana plugins we need at runtime, and lock them to a specific version - means the image becomes more portable, and also usable in an air-gapped deployment.
Testing:
* Built an image, ensured it runs and the plugin we need is usable
* Added smoke test to cover plugin installation
* make TEST_SUITE=smoke test-containers
> CMOS-115 Install Grafana plugins at runtime

- microlith/grafana/grafana.ini
- microlith/grafana/provisioning/dashboards/cluster-overview.json
- microlith/grafana/provisioning/dashboards/couchbase-inventory.json
* Renamed "Cluster Overview" dashboard to "Couchbase Inventory"
* Reordered the table headings so the important stuff appears first
* Renamed the table headings
* Added links to the Cluster UI and made the cluster name link to the individual dashboard.
> CMOS-74: Rename Inventory Dashboard

- CONTRIBUTING.md
- testing/bats/smoke/couchbase-exporter.bats
- testing/helpers/couchbase-helpers.bash
- testing/helpers/native-helpers.bash
- testing/helpers/test-helpers.bash
- testing/resources/containers/cb-with-exporter.Dockerfile
- testing/resources/containers/run_exporter.sh
This PR improves the smoke suite by:
* Initialising the Couchbase Server cluster
* Adding the Prometheus Exporter to the CB nodes in Containers tests, and
* Testing that both of the above worked, by querying `cbnode_up==1`
> Smoke: initialise CB clusters, add Prometheus exporter, and test it all works

- config-svc/pkg/api/routes_v1.go
- microlith/html/promwebform.html
The add cluster form sets a label called `cluster` which is the name the user gives it, but the Exporter also exposes a field called `cluster` which is the name of the cluster as given to CB. This commit changes the name of the field added by the form to `cluster_label`. (I didn't use `cluster_name` as the Cluster Monitor uses that name for its metrics - they're on a different job, so they wouldn't get clobbered, but the names would still be inconsistent.)
> CMOS-131: Avoid clobbering `cluster` label when adding a cluster

- microlith/Dockerfile
Changelogs:
* Prometheus 2.28.1 -> 2.31.0: https://github.com/prometheus/prometheus/blob/release-2.31/CHANGELOG.md
* Alertmanager 0.22.2 -> 0.23.0: https://github.com/prometheus/alertmanager/blob/release-0.23/CHANGELOG.md
* Grafana 8.1.1 -> 8.2.3: https://github.com/grafana/grafana/blob/v8.2.3/CHANGELOG.md
* Jaeger 1.25.0 -> 1.27.0: https://github.com/jaegertracing/jaeger/blob/v1.27.0/CHANGELOG.md
Ran the tests, and also verified that all core functions work after running the built image manually.
> CMOS-139: Update base images

- microlith/html/promwebform.html
The `cluster` label on the `couchbase-server` jobs is unnecessary - the Exporter sets a label `cluster` and cbmultimanager sets `cluster_name` and `cluster_uuid`. If we set one at the job level it'll get clobbered or renamed to `exported_cluster` which may break the dashboards.
Remove the field entirely to avoid the need to keep around various versions of it. The generated Prometheus targets file will be named after the first node in the cluster (sanitised for a file name).
We may need to revisit this when we move to CB7's Prometheus, as I don't think it sets a `cluster` label - but for now this should be sufficient.
> CMOS-131 Remove cluster name label

- docs/modules/ROOT/nav.adoc
- microlith/html/index.html
For v0.1 we're not going to have the UI as a feature - it'll still be there in case we need to debug the cluster monitor's behaviour, but it won't be user-facing. Remove the links from our navigation - both on the HTML landing page and in Antora.
> CMOS-144: Remove navigation links to Cluster Monitor UI

- README.md
- docs/modules/ROOT/pages/index.adoc
In https://github.com/couchbaselabs/observability/commit/de00a275776997318dc74f696e9a8cdb79e86fc5 we renamed "Prometheus Add Endpoint" to "Add Cluster". Update the quick start guide in the README to match.
> Update quick start guide for Add Cluster renaming

- microlith/grafana/provisioning/dashboards/couchbase-inventory.json
- microlith/grafana/provisioning/dashboards/single-cluster-overview-7.json
This commit adds a version of the single-cluster-overview dashboard compatible with CBS 7.x. It keeps around the 6.x version for the time being, but the Couchbase Inventory will now link to 7.x.
This PR is independent of #79, though testing it will require configuring CMOS the "old-fashioned way" (i.e. `docker cp`, not the GUI) until that PR is merged.
> CMOS-143: Add improved CB7 single-cluster overview dashboard

- docs/modules/ROOT/pages/quickstart.adoc
The QSG never actually says that you need Docker, it's implied. Explicitly add it.
> Add prerequisites to quick-start guide

- microlith/grafana/provisioning/dashboards/couchbase-inventory.json
- microlith/grafana/provisioning/dashboards/single-cluster-overview-7.json
- microlith/grafana/provisioning/dashboards/single-cluster-overview.json
- Add link to Add Cluster page on the inventory dashboard
- Add tags to the inventory dashboard, and link back to it from the single-cluster dashboards
> Tweak dashboard interlinking

- examples/containers/.env
- examples/containers/README.md
- examples/containers/configure-cbs.sh
- examples/containers/docker-compose-exporter.yml
- examples/containers/docker-compose.yml
- examples/containers/run.sh
- examples/containers/stop.sh
Switched to using the official image although this will need an update for release.
Now sets up Couchbase Server using the generic entrypoint to ensure we have a bucket, etc. declaratively similar to what the server-sandbox image did but for any image.
> Container example updates

- Makefile
- examples/containers/.env
- examples/containers/README.md
- examples/containers/run.sh
- tools/build-oss-container.sh
Resolves: https://issues.couchbase.com/browse/CMOS-158
Switch to always building the images for now, once we have a released version that is what the examples should default to with instructions for developers to build locally or a separate compose stack.
> CMOS-158: Always build CMOS container for examples until 0.1 release

- examples/containers/README.md
- examples/containers/run.sh
- examples/kubernetes/README.md
- examples/kubernetes/run.sh
Add optional container build to the `run.sh` script.
The `Makefile` target does run the `container` target first though anyway.
> CMOS-158: Update example docs

- microlith/html/promwebform.html
As part of code review for https://github.com/couchbaselabs/observability/pull/79, I changed the variable `secure` to `useTLS`, but missed some places: this fixes the last remaining one. This wasn't caught because we don't test the form with TLS-enabled clusters - perhaps we should.
> Fix incorrect reference to `secure` as opposed to `useTLS`

- examples/kubernetes/README.md
- examples/kubernetes/custom-values.yaml
- examples/kubernetes/run.sh
Resolves https://issues.couchbase.com/browse/CMOS-163 due to slight race condition between marking pods as ready and traffic reaching them correctly. Simple solution is best so just retry. Also updated to follow the slight changes in the official Kind ingress documentation as well: https://kind.sigs.k8s.io/docs/user/ingress/
Modified slightly to also make the ingress optional per some of the documentation discussions but also as a few of the links for the tooling do not function correctly with it. This also means we can run multiple isolated clusters as well.
> CMOS-163: Resolve issue with Ingress and make optional

- CONTRIBUTING.md
- docs/antora-container-playbook.yml
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/support.adoc
Some parts of the docs only make sense when packaged inside the container, while others only make sense outside it. This commit introduces the `env-packaged` attribute, which can be used in an AsciiDoc `ifdef` to have conditional content.
For example, when built inside the container, the Support page links directly to the collect info form, while when built outside it instead has the URL of the form.
> Allow conditional docs contents for the packaged environment

- testing/bats/integration/kubernetes/standalone.bats
- testing/helpers/test-helpers.bash
We changed the logging format which the tests depended on. Update the tests to match.
Tested on https://github.com/couchbaselabs/observability/actions/runs/1480417033 - native tests are still running but k8s has already passed:
```
ok 4 Verify disabling of components in microlith in 101054ms
```
> Fix k8s test failure after CMOS-168 changes

- microlith/promtail/config-microlith.yaml
- testing/bats/smoke/prometheus-metrics.bats
Enabling auto-merge as well to check it is preventing merge on action failures
> Resolve failures from auto-merge 

- microlith/Dockerfile
I observed a segfault in the cluster monitor, which was reported on the Go issue tracker (https://github.com/golang/go/issues/30310#issuecomment-471669125). This appears to be caused by using cgo with `-extldflags "-static"` without `-tags netgo`. This commit changes all our Cgo enabled components to be built with `-tags netgo`.
> CMOS-177 Use `-tags netgo` for cgo builds

- microlith/run.sh
- testing/bats/smoke/prometheus-metrics.bats
In some cases we have seen Promtail crash immediately upon startup - see CMOS-179 for details. This appears to be either machine-specific, or related to some configuration.
Disable Promtail by default as a workaround. We don't actually have any dashboards that make use of Promtail's logging, so we don't lose anything.
I'll convert CMOS-179 into a tracking issue for re-enabling it.
> CMOS-179: Disable Promtail by default as a workaround for crash issues

- Makefile
Previously `docker image prune --force` was used to remove all untagged images that may be left.
By making `container-clean` depend on `examples-clean`, we ensure that any dependent containers are removed first, and so `docker rmi` successfully both untags and deletes the image as required.
> - Update makefile to remove force prune while cleaning up containers

- examples/containers/multi/helpers/driver.sh
- examples/containers/multi/stop.sh
- For some reason Docker would not remove anonymous created by containers run with the --rm arg when said containers stop, as should happen.
This is an alternative (working) method.
> Remove prune from multi/stop.sh, Fix anonymous volumes not being removed

- microlith/Dockerfile
We should probably pull in 8.3.x at some point soon, but for now upgrade to 8.2.7 as it's less risky.
Gave it a local build as a sanity check, everything appears to work, and the changelog between 8.2.5 and 8.2.7 is relatively short:
```
8.2.7 (2021-12-07)
Security: Fixes CVE-2021-43798. For more information, see our blog
8.2.6 (2021-12-02)
Features and enhancements
Security: Upgrade Docker base image to Alpine 3.14.3. #42061, @dsotirakis
Security: Upgrade Go to 1.17.2. #42427, @idafurjes
Bug fixes
TimeSeries: Fix fillBelowTo wrongly affecting fills of unrelated series. #41998, @leeoniya
```
> CMOS-212: Upgrade Grafana to 8.2.7

- .github/dependabot.yml
The configuration syntax should be correct (cf. https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#about-the-dependabotyml-file), but as far as I can tell there's no way to test it apart from seeing if it works
> Configure Dependabot to automatically check for updates to Docker base images

- docs/antora.yml
This change will add a `Developer Preview` label on each CMOS page when the doc site is built.
In future, when we're out of DP, the `antora.yml` will need to be updated to remove this attribute.
See the image below from my local build for an idea of what this looks like:
> Add Developer Preview label to each doc page

- microlith/grafana/provisioning/dashboards/bucket-overview.json
For some reason certain panels in this dashboard duplicated themselves. This causes an error when you attempt to resize them. In some cases you can move the front panel away from the back panel to reveal it  (or by deleting the front one), and in others you can move them over one another.
This aims to fix this behaviour by removing the offending panels.
> bucket-overview: remove ghost panels

- microlith/grafana/provisioning/dashboards/cluster-overview.json
When a node is failed over, Cluster Monitor can stop reporting its CPU and RAM totals, which will cause JSONata processing errors. Explicitly handle the case where they're missing.
> Cluster Overview: fix nodes panel error when node is failed over

- microlith/loki/alerting/couchbase/couchbase-rules.yaml
I accidentally used ${{ labels... }} instead of {{ $labels...}, meaning the rules file failed to parse.
Filed CMOS-250 to prevent this from happening again.
> CMOS-249: Fix invalid Loki rules

- microlith/Dockerfile
- microlith/Dockerfile.rhel
Ensure it has the directories it expects on startup, otherwise it won't execute the rules
> CMOS-249: More Loki fixups

- microlith/entrypoints/loki.sh
- microlith/loki/alerting/couchbase/test-rules.yaml
- microlith/loki/config.yml
- microlith/loki/scripts/loki_alerts_prepare.sh
- microlith/nginx/nginx.conf
- testing/bats/smoke/loki-sanity-check.bats
- testing/helpers/test-helpers.bash
Add a test case that checks if Loki is properly evaluating alerting rules and sending alerts to Alertmanager. This should hopefully ensure a situation like CMOS-249 cannot happen again.
There's some test-specific configuration in the Loki config file - this is solely to ensure tests don't take too long. The testing rules file is deleted by loki_alerts_prepare.sh unless explicitly told not to, so the impact in production should be minimal.
> CMOS-250: Add smoke test for Loki alerts

- microlith/loki/config.yml
The syntax for env-substitution was slightly wrong in the Loki config file (will raise an upstream docs issue to correct it), and so it would panic on startup.
> CMOS-250: Quick-fix for Loki startup panics

- microlith/grafana/provisioning/dashboards/bucket-overview.json
- microlith/grafana/provisioning/dashboards/cluster-overview.json
- microlith/grafana/provisioning/dashboards/node-overview.json
- microlith/loki/alerting/couchbase/test-rules.yaml
Since we plumbed Cluster Monitor into Alertmanager, these panels picked up its alerts, in addition to the checker data they were getting via Prometheus.
Restrict the query to only Prometheus/Loki-triggered alerts.
> CMOS-257: Fix duplicate health check issues in dashboards

- .aspell.en.pws
- docs/modules/ROOT/partials/cmos-health-checks.adoc
- microlith/loki/alerting/couchbase/couchbase-rules.yaml
These alerts are intended to be temporary until it is decided if/how an agent will be used in CMOS.
> CMOS-248: Add Alerts for Service Crashes

- config-svc/pkg/api/routes_v1.go
- config-svc/pkg/api/routes_v1_test.go
- config-svc/pkg/api/v1/cmos_config_api.yaml
- config-svc/pkg/api/v1/generated.go
- microlith/html/promwebform.html
People may have their Prometheus exporters on ports other than 9091. Give them an option to override it, while still using the management port for 7.0 clusters.
> CMOS-271: Allow overriding metrics port when adding cluster

- microlith/grafana/provisioning/dashboards/cluster-overview.json
In the single cluster overview dashboard we were missing a filter for the cluster in our requests to Alertmanager.
> CMOS-279: Ensure we don't mix alerts from different clusters

- .github/workflows/pr-loki.yml
- .gitignore
- Makefile
- microlith/loki/alerting/couchbase/couchbase-rules.yaml
- testing/helpers/url-helpers.bash
- testing/loki_alerts/Couchbase-Server/CB90033-longDcpNames-failedResponse/memcached.log.000000.txt
- testing/loki_alerts/Couchbase-Server/CB90036-memcachedCrash/memcached.log.000000.txt
- testing/loki_alerts/Couchbase-Server/CB90037-slowOperations/memcached.log.000000.txt
- testing/loki_alerts/Couchbase-Server/CB90044-babysitterManagedProcessCrash/babysitter.log
- testing/loki_alerts/README.md
- testing/loki_alerts/fluent-bit.header.conf
- testing/loki_alerts/fluent-bit.trailer.conf
- testing/loki_alerts/rebase_times.lua
- testing/loki_alerts/run_all.sh
- testing/loki_alerts/run_single_test.sh
Add a framework for importing a set of logs into Loki (using Fluent Bit), and then asserting that the relevant alerting rule's query matches. Also add a GitHub Action to run it.
Note that this won't test the labels sent to Alertmanager (as that'd be too slow), only whether the query matches.
> CMOS-250: Add unit tests for Loki rules

- testing/bats/integration/kubernetes/standalone.bats
We used to specifically require a 404 in the test for Loki being disabled - at some point nginx started returning a 502 instead. Instead of requiring a specific error code, just check if we got an error.
> CMOS-311: Fix Kubernetes tests

- docs/modules/ROOT/partials/cmos-health-checks.adoc
- microlith/loki/alerting/couchbase/couchbase-rules.yaml
- microlith/prometheus/alerting/couchbase/couchbase-rules.yaml
There's also a Hazelnut rule in https://review.couchbase.org/c/cbmultimanager/+/170676.
> CMOS-278: Add alert for KV connection limit

- microlith/grafana/provisioning/dashboards/bucket-overview.json
- microlith/grafana/provisioning/dashboards/cluster-overview.json
- microlith/grafana/provisioning/dashboards/node-overview.json
Ensure we link to somewhere they'll be accessible even if the dashboards are installed outside the microlith.
> CMOS-338: Replace all checker docs links with public site

- docs/modules/ROOT/pages/quickstart.adoc
Note that this isn't live yet, but will be by the time these docs are published.
> CMOS-219: Update quick-start guide to reference Docker image

- docs/modules/ROOT/pages/integrating-with-existing-deployments.adoc
The intention is that this PR will be reverted once there is a separate 0.2.x branch for the live docs - this will ensure that the packaged docs in the container do not have references to the agent, nor will the docs.couchbase version, but the docs-staging.couchbase version will.
> CMOS-353: Remove agent details from docs

- microlith/grafana/provisioning/dashboards/bucket-overview.json
- microlith/grafana/provisioning/dashboards/cluster-overview.json
- microlith/grafana/provisioning/dashboards/node-overview.json
This isn't live yet, but will be necessary once the public DP is released. Once that's done and we've branched for release, we can likely revert it back on `main` which will track latest docs.
> CMOS-352: Dashboards: replace all references to docs-staging.couchbase with docs.couchbase

- CONTRIBUTING.md
- README.md
Expand on existing information about getting started with and contributing to the CMOS project. This information is currently spread over several repos or missing altogether. This commit aims to consolidate all the information needed to start contributing to CMOS in the top-level (observability) repo.
> CMOS-407: Expand details about contributing to observability repo

- .github/workflows/trivy-analysis.yml
Action config was referencing a tag that no longer exists.
> CBD-4609: Fix Trivy scans

- docs/modules/ROOT/partials/cmos-health-checks.adoc
- microlith/prometheus/alerting/couchbase/couchbase-rules.yaml
Checker to alert and warn when active vbucket resident ratio in memory drops below a threshold (warning below 10 percent and alert below 5 percent)
> CMOS-395: Active vbuckets resident ratio checker

- microlith/nginx/nginx.conf.tmpl
Multimanager UI sits on /couchbase/ui not /ui
This simplifies the required NGINX config
> CMOS-425: Updated nginx config for multimanager UI
