couchbaselabs/observability

- microlith/Dockerfile
- microlith/grafana/cmos-doc-redirect.html
- microlith/grafana/provisioning/dashboards/single-cluster-overview.json
> Include checker docs in doc build, and link to them from Grafana

- .github/workflows/pr-screenshots.yml
- Makefile
- microlith/Dockerfile
- microlith/Dockerfile.rhel
- tools/build-oss-container.sh
- tools/generate-screenshots.sh
- tools/hadolint.sh
- tools/licence-lint.sh
- tools/shellcheck.sh
Primarily to fix the failures on the action which we could not test until it was merged.
This also uploads the screenshots taken to the action run.
> Auto screenshot improvements

- microlith/Dockerfile
- microlith/Dockerfile.rhel
> Update Loki base versions

- .aspell.en.pws
Egg on my face for merging before checking the lint status...
> Add macOS to spellcheck dictionary

- .aspell.en.pws
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/prerequisite-and-setup.adoc
- docs/modules/ROOT/pages/quickstart.adoc
Simple placeholder for basic prerequisite and setup page.
> CMOS-127: add resolution and other pre-requisite info

- microlith/grafana/provisioning/dashboards/bucket-overview-7.json
- microlith/grafana/provisioning/dashboards/couchbase-inventory.json
- microlith/grafana/provisioning/dashboards/node-overview-7.json
- microlith/grafana/provisioning/dashboards/service-kv-7.json
- microlith/grafana/provisioning/dashboards/service-n1ql-7.json
- microlith/grafana/provisioning/dashboards/single-cluster-overview-7.json
These will likely change considerably before being shipped to customers, this is just as a starting point.
> Add dashboards from Show & Tell demo

- microlith/html/promwebform.html
> CMOS-165: Validate and sanitize add cluster form inputs

- examples/kubernetes/prometheus/custom/prometheus-k8s.yml
- examples/kubernetes/stop.sh
Pulls in `couchbase_cluster` value as `cluster` value for metrics: https://issues.couchbase.com/browse/CMOS-160
> CMOS-160: Add relabel support for dashboards

- CONTRIBUTING.md
Initial guidance, as always can and should be evolved.
@princerachit 
@anilkumar29
> Add contribution guidance for docs

- .ansible-lint
- .github/workflows/cron-build.yml
- .github/workflows/pr-main-build.yml
- .gitignore
- microlith/scripts/collect-information.sh
- testing/bats/integration/kubernetes/resources/prometheus/prometheus-default-config.yaml
- testing/bats/integration/kubernetes/standalone.bats
- testing/bats/smoke/prometheus-metrics.bats
- testing/bats/smoke/prometheus-sd.bats
- testing/helpers/native-helpers.bash
- testing/helpers/test-helpers.bash
- testing/resources/native/playbook.yml
- testing/test-common.sh
- tools/licence-lint.sh
- tools/shellcheck.sh
* Don't use CNPE with CB7
* Use config-svc to configure Prometheus in native/containers
* Capture cmosinfo if the tests or setup fail
> Update tests for CB7, config-svc, and cmosinfo

- Makefile
- tools/dashboards-lint.sh
Catch some common export issues (exporting for external use, which has problems with provisioning, and exporting using absolute time ranges)
> Add linting for dashboards

- microlith/Dockerfile
- microlith/Dockerfile.rhel
Upgrade:
* Prometheus 2.31.0 -> 2.31.1 [changelog](https://github.com/prometheus/prometheus/releases/tag/v2.31.1)
* Jaeger 1.27.0 -> 1.29.0 [changelog 1.28.0](https://github.com/jaegertracing/jaeger/releases/tag/v1.28.0), [1.29.0](https://github.com/jaegertracing/jaeger/releases/tag/v1.29.0)
* Red Hat UBI 8.4 -> 8.5
* UBI Toolset 1.15.14-3 -> 1.15.14-18
> Update Docker base images

- docs/antora.yml
https://issues.couchbase.com/browse/DOC-9503
I'm not 100% sure if this will fix it, but it's the only thing I can see that is missing...
> DOC-9503 - Sidebar navigation links broken

- .aspell.en.pws
- docs/modules/ROOT/partials/cmos-health-checks.adoc
- microlith/prometheus/alerting/couchbase/couchbase-rules.yaml
> CMOS-238: Add CPU Steal Prometheus Alert

- docs/modules/ROOT/partials/cmos-health-checks.adoc
- microlith/loki/alerting/couchbase/couchbase-rules.yaml
Please double check the YAML/LogQL quite thoroughly,
my first attempt at writing a query so likely to include
some errors.
> CMOS-247: Add Babysitter Managed Service Crash Check

- .aspell.en.pws
- docs/modules/ROOT/partials/cmos-health-checks.adoc
- microlith/loki/alerting/couchbase/couchbase-rules.yaml
Tested LogQL manually on live cluster
> CMOS-258: Add Malformed vBucket Alert

- docs/modules/ROOT/partials/cmos-health-checks.adoc
- microlith/prometheus/alerting/couchbase/couchbase-rules.yaml
Tested PromQL in live Cluster.
> CMOS-263: Add Metadata Overhead Alert

- .aspell.en.pws
- docs/modules/ROOT/pages/index.adoc
Document DP limitations and known issues (#168)
Co-authored-by: Maria Shodunke <maria-robobug@users.noreply.github.com>
Co-authored-by: Anil Kumar <anilkumar29@users.noreply.github.com>
> Backport #168 onto 0.1.x branch

- microlith/Dockerfile
- microlith/grafana/provisioning/dashboards/bucket-overview.json
- microlith/grafana/provisioning/dashboards/check-history.json
- microlith/grafana/provisioning/dashboards/cluster-overview.json
- microlith/grafana/provisioning/dashboards/configuration-check.json
- microlith/grafana/provisioning/dashboards/couchbase-inventory.json
- microlith/grafana/provisioning/dashboards/node-overview.json
- microlith/grafana/provisioning/dashboards/service-data.json
- microlith/grafana/provisioning/dashboards/service-eventing.json
- microlith/grafana/provisioning/dashboards/service-index.json
- microlith/grafana/provisioning/dashboards/service-query.json
- microlith/grafana/provisioning/dashboards/service-search.json
- microlith/grafana/provisioning/datasources/datasource.yml
There were some slight changes to the dashboard data model, so upgrade them to match. Also, since data sources now have UIDs, update our provisioning to use them too.
> CMOS-215: Upgrade Grafana to 8.3.x

- microlith/grafana/README.md
- microlith/grafana/provisioning/dashboards/bucket-overview.json
- microlith/grafana/provisioning/dashboards/check-history.json
- microlith/grafana/provisioning/dashboards/cluster-overview.json
- microlith/grafana/provisioning/dashboards/configuration-check.json
- microlith/grafana/provisioning/dashboards/couchbase-inventory.json
- microlith/grafana/provisioning/dashboards/node-overview.json
- microlith/grafana/provisioning/dashboards/service-data.json
- microlith/grafana/provisioning/dashboards/service-eventing.json
- microlith/grafana/provisioning/dashboards/service-index.json
- microlith/grafana/provisioning/dashboards/service-query.json
- microlith/grafana/provisioning/dashboards/service-search.json
- microlith/grafana/provisioning/datasources/datasource.yml
- tools/dashboards-lint.sh
Switch to using Share for External Use with template variables for all data sources we use, to avoid issues with the "default" data source. Update linting to match.
> CMOS-333: Rework dashboard provisioning model

- docs/modules/ROOT/pages/index.adoc
- docs/modules/ROOT/pages/integrating-with-existing-deployments.adoc
- docs/modules/ROOT/pages/support.adoc
- docs/modules/ROOT/pages/tutorial-kubernetes.adoc
* Update list of known issues
* Remove unused parts of kubernetes tutorial
* Add minimum versions of Prometheus/Grafana/Loki for on-prem
> Final DP1 docs fixups

- .github/workflows/pr-main-build.yml
- .gitignore
- Makefile
- microlith/Dockerfile
- tools/build-container-from-archive.sh
Do not merge until the corresponding manifest and cbmultimanager changes are in.
> CBD-4609: Refactor build process

- .ansible-lint
- .github/workflows/pr-main-build.yml
- Makefile
- tools/build-container-from-archive.sh
Depends on https://review.couchbase.org/c/cbmultimanager/+/172977, do not merge until that is in.
> CMOS-351: Properly package couchbase-cluster-monitor image

- docs/modules/ROOT/pages/release-notes.adoc
- tools/release_notes.go
Generates release notes automatically based off Jira releases 🎈
> CMOS-459 Release note generation

- docs/modules/ROOT/pages/health-agent.adoc
- tools/release_notes.go
updated docs to contains cbhealth agent dl links
also included a change to make sure we're getting all the issues from the release docs generation.
> CMOS-460 add cbhealthagent dl links
